// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq4ff8C5-5CUN2ZkjBmjn4_1C0gEbKio0',
    appId: '1:949411018782:web:e3aff94c6974102c0d960f',
    messagingSenderId: '949411018782',
    projectId: 'task2-6378f',
    authDomain: 'task2-6378f.firebaseapp.com',
    storageBucket: 'task2-6378f.firebasestorage.app',
    measurementId: 'G-NZVV857C40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ8o4-aGNzmjvTYinHeAlDUezi8rGwHPE',
    appId: '1:949411018782:android:2ad7427c812d64520d960f',
    messagingSenderId: '949411018782',
    projectId: 'task2-6378f',
    storageBucket: 'task2-6378f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQBd5CpWIkEzVoMqw_l8EoRfN7AUO2UAo',
    appId: '1:949411018782:ios:40d10cb4eca8bb9a0d960f',
    messagingSenderId: '949411018782',
    projectId: 'task2-6378f',
    storageBucket: 'task2-6378f.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQBd5CpWIkEzVoMqw_l8EoRfN7AUO2UAo',
    appId: '1:949411018782:ios:40d10cb4eca8bb9a0d960f',
    messagingSenderId: '949411018782',
    projectId: 'task2-6378f',
    storageBucket: 'task2-6378f.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq4ff8C5-5CUN2ZkjBmjn4_1C0gEbKio0',
    appId: '1:949411018782:web:a99defb015f2ebfc0d960f',
    messagingSenderId: '949411018782',
    projectId: 'task2-6378f',
    authDomain: 'task2-6378f.firebaseapp.com',
    storageBucket: 'task2-6378f.firebasestorage.app',
    measurementId: 'G-Y2J61YSK0C',
  );
}
